import { NextRequest,NextResponse } from 'next/server';
import { randomUUID } from 'crypto';
import { assertLocal } from '@/lib/evidence/access';
import { commitIntake,intakeWorkspace } from '@/lib/evidence/repository';
import type { DatasetType } from '@/lib/evidence/model';
import { MAPPING_VERSION } from '@/lib/intake/interpreter';
import { normalizeSheet } from '@/lib/intake/normalize';
import { removeStage,staged } from '@/lib/intake/staging';
export const runtime='nodejs';export const dynamic='force-dynamic';
const datasets=new Set<DatasetType>(['profit_and_loss','balance_sheet','general_ledger','transactions','invoices','payments','bills','expenses','customers','vendors','jobs','technicians','payroll','time_entries','estimates','callbacks','materials','inventory','marketing','lead_sources','advertising','generic']);
export async function POST(req:NextRequest){try{assertLocal(req,true);if(Number(req.headers.get('content-length')||0)>2_000_000)throw new Error('Commit request exceeds the 2 MB limit.');const body=await req.json() as {uploadId?:string;businessId?:string;sheetIndex?:number;datasetType?:DatasetType;mappings?:Array<{sourceColumn:string;targetField:string;confirmed:boolean}>;currency?:string;complete?:boolean;basis?:string;sourceSystem?:string};const businessId=String(body.businessId||'');if(!body.uploadId||!Number.isInteger(body.sheetIndex)||!Array.isArray(body.mappings))throw new Error('Upload, worksheet and reviewed mappings are required.');const upload=await staged(body.uploadId,businessId);const sheet=upload.sheets[body.sheetIndex!];if(!sheet)throw new Error('Worksheet was not found in this staged file.');const datasetType=body.datasetType||sheet.classification;if(!datasets.has(datasetType))throw new Error('Unsupported dataset classification.');const mappings=body.mappings.map(m=>{const suggested=sheet.mappings.find(s=>s.sourceColumn===m.sourceColumn);if(!suggested)throw new Error('Mapping references a column not present in the staged file.');const changed=m.targetField!==suggested.targetField;return {...suggested,targetField:m.targetField,confidence:changed?0.5:suggested.confidence,confirmed:m.confirmed===true,reason:changed?'Owner-selected mapping; requires explicit confirmation.':suggested.reason};});const current=await intakeWorkspace(businessId);const id=randomUUID();const normalizedResult=normalizeSheet({businessId,importId:id,fileName:upload.fileName,fileType:upload.fileType,sourceSystem:String(body.sourceSystem||'Manual upload').slice(0,100),sheet:{...sheet,classification:datasetType},mappings,currency:String(body.currency||''),complete:body.complete===true,basis:typeof body.basis==='string'?body.basis:'',existing:current.normalized});const now=new Date().toISOString();const batch={id,businessId,fileName:upload.fileName,fileType:upload.fileType,datasetType,sourceSystem:String(body.sourceSystem||'Manual upload').slice(0,100),status:'COMMITTED' as const,rowCount:sheet.rows.length,acceptedCount:normalizedResult.normalized.filter(r=>r.quality==='ACCEPTED').length,duplicateCount:normalizedResult.duplicateCount,invalidCount:normalizedResult.invalidCount,sourceDigest:upload.digest,mappingVersion:MAPPING_VERSION,mappings,createdAt:now,warnings:normalizedResult.warnings};await commitIntake({batch,normalized:normalizedResult.normalized,records:normalizedResult.records});await removeStage(upload.id);const updated=await intakeWorkspace(businessId);return NextResponse.json({success:true,import:batch,analysis:updated.analysis,normalizedCount:normalizedResult.normalized.length,financialEvidenceCount:normalizedResult.records.length,warnings:normalizedResult.warnings},{headers:{'Cache-Control':'no-store'}});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Import was not committed.'},{status:400});}}
