import { NextRequest,NextResponse } from 'next/server';
import path from 'path';
import { assertLocal } from '@/lib/evidence/access';
import { createBusiness,intakeWorkspace,listBusinesses } from '@/lib/evidence/repository';
import { capabilityReport } from '@/lib/intake/capabilities';
import { digestRows,MAX_FILE_BYTES,parseCsv,parseXlsx } from '@/lib/intake/interpreter';
import { removeStage,stage,staged,StagedUpload } from '@/lib/intake/staging';
export const runtime='nodejs';export const dynamic='force-dynamic';
export async function GET(req:NextRequest){try{assertLocal(req);const businesses=await listBusinesses(),businessId=req.nextUrl.searchParams.get('businessId')||businesses[0]?.id;if(!businessId)throw new Error('Create a business workspace first.');const data=await intakeWorkspace(businessId),capabilities=capabilityReport(data.normalized,data.sourceRecords,data.imports);return NextResponse.json({businesses, ...data,capabilities},{headers:{'Cache-Control':'no-store'}});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to load intake data.'},{status:400});}}
export async function POST(req:NextRequest){try{assertLocal(req,true);if(Number(req.headers.get('content-length')||0)>32*1024*1024)throw new Error('Request exceeds the 32 MB upload batch limit.');const ct=req.headers.get('content-type')||'';let businessId='',files:File[]=[];if(ct.includes('multipart/form-data')){const form=await req.formData();businessId=String(form.get('businessId')||'');files=form.getAll('files').filter((v):v is File=>v instanceof File);}else{const body=await req.json();businessId=String(body.businessId||'');if(body.manual){const manual=body.manual as {name?:string;date?:string;amount?:string;currency?:string;metric?:string;description?:string};const headers=['Date','Amount','Currency','Reference'],metric=String(manual.metric||'revenue');const sheet={name:'Manual entry',headers,rows:[{'Date':String(manual.date||''),'Amount':String(manual.amount||''),'Currency':String(manual.currency||''),'Reference':String(manual.description||'Manual entry')}],classification:'generic' as const,dateRange:null,mappings:[{sourceColumn:'Date',targetField:'date',confidence:1,reason:'Entered directly by the owner.',confirmed:true},{sourceColumn:'Amount',targetField:metric,confidence:1,reason:'Selected explicitly by the owner.',confirmed:true},{sourceColumn:'Currency',targetField:'currency',confidence:1,reason:'Entered by the owner.',confirmed:true},{sourceColumn:'Reference',targetField:'transaction_id',confidence:1,reason:'Manual reference.',confirmed:true}]};const created=await stage({businessId,fileName:(manual.name||'Manual entry').slice(0,120),fileType:'manual',digest:digestRows(sheet),sheets:[sheet]});return NextResponse.json({uploads:[summarize(created)]});}}
 const businesses=await listBusinesses();if(!businesses.some(b=>b.id===businessId))throw new Error('Select a known business workspace.');if(!files.length||files.length>4)throw new Error('Upload between 1 and 4 files per batch.');const total=files.reduce((n,f)=>n+f.size,0);if(total>24*1024*1024)throw new Error('Combined file size limit is 24 MB.');const uploads:unknown[]=[],errors:unknown[]=[];for(const file of files){try{if(file.size>MAX_FILE_BYTES)throw new Error('File exceeds 8 MB.');const fileName=path.basename(file.name).replace(/[\x00-\x1f]/g,'').slice(0,200);const ext=path.extname(fileName).toLowerCase();if(!['.csv','.xlsx'].includes(ext))throw new Error(ext==='.xls'?'Legacy .xls parsing is intentionally unsupported; save as .xlsx or .csv.':'Only .csv and .xlsx are supported.');const bytes=Buffer.from(await file.arrayBuffer());let sheets;if(ext==='.csv'){const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes).replace(/^\uFEFF/,'');sheets=parseCsv(text,fileName);}else sheets=await parseXlsx(bytes,fileName);const item=await stage({businessId,fileName,fileType:ext==='.csv'?'csv':'xlsx',digest:digestRows(sheets),sheets});uploads.push(summarize(item));}catch(e){errors.push({fileName:file.name,error:e instanceof Error?e.message:'File failed validation.'});}}
 return NextResponse.json({uploads,errors},{status:uploads.length?200:400});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Upload rejected safely.'},{status:400});}}
function summarize(item:StagedUpload){return {uploadId:item.id,businessId:item.businessId,fileName:item.fileName,fileType:item.fileType,digest:item.digest,createdAt:item.createdAt,sheets:item.sheets.map((s,index)=>({index,name:s.name,classification:s.classification,headers:s.headers,rows:s.rows.length,dateRange:s.dateRange,mappings:s.mappings,preview:s.rows.slice(0,5)}))};}
export async function DELETE(req:NextRequest){try{assertLocal(req,true);const id=req.nextUrl.searchParams.get('uploadId'),businessId=req.nextUrl.searchParams.get('businessId');if(!id||!businessId)throw new Error('Upload and business IDs required.');await staged(id,businessId);await removeStage(id);return NextResponse.json({success:true});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to remove staged upload.'},{status:400});}}
