import { createHash,randomBytes,timingSafeEqual } from 'crypto';
import { prisma } from '@/lib/db';
import { encryptSecret,decryptSecret } from './crypto';
import { apiBase,authorizeEndpoint,qboConfig,tokenEndpoint,revokeEndpoint,QboEnvironment } from './config';
export const QBO_BUSINESS_ID='local-workspace';
const scopes='com.intuit.quickbooks.accounting';
export function sha(value:string){return createHash('sha256').update(value).digest('hex');}
export function secureEqual(a:string,b:string){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);}
export async function createAuthorization(){const cfg=qboConfig();if(!process.env.BIZBETTER_SECRET_ENCRYPTION_KEY)throw new Error('Configure the server-side encryption key before connecting QuickBooks.');const state=randomBytes(32).toString('base64url');await prisma.oAuthState.deleteMany({where:{expiresAt:{lt:new Date()}}});await prisma.oAuthState.create({data:{stateHash:sha(state),environment:cfg.environment,expiresAt:new Date(Date.now()+10*60_000)}});const url=new URL(authorizeEndpoint);url.searchParams.set('client_id',cfg.clientId);url.searchParams.set('response_type','code');url.searchParams.set('scope',scopes);url.searchParams.set('redirect_uri',cfg.redirectUri);url.searchParams.set('state',state);return {url:url.toString(),state};}
interface TokenResponse {access_token:string;refresh_token:string;expires_in:number;x_refresh_token_expires_in:number;token_type?:string;scope?:string;}
async function postToken(body:URLSearchParams){const cfg=qboConfig();let response:Response;try{response=await fetch(tokenEndpoint,{method:'POST',redirect:'error',headers:{Authorization:'Basic '+Buffer.from(cfg.clientId+':'+cfg.clientSecret).toString('base64'),'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'},body,cache:'no-store',signal:AbortSignal.timeout(20000)});}catch{throw new Error('QuickBooks OAuth token service is unavailable.');}if(!response.ok)throw new Error('QuickBooks OAuth authorization or refresh failed with status '+response.status+'. Reconnect if the provider rejected the grant.');const data=await response.json() as TokenResponse;if(typeof data.access_token!=='string'||typeof data.refresh_token!=='string'||!Number.isSafeInteger(data.expires_in)||!Number.isSafeInteger(data.x_refresh_token_expires_in))throw new Error('QuickBooks returned an invalid token response.');return data;}
export async function exchangeCode(code:string,realmId:string,environment:QboEnvironment){if(!/^\d{1,32}$/.test(realmId)||code.length>4096)throw new Error('Invalid QuickBooks callback values.');const cfg=qboConfig();const token=await postToken(new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:cfg.redirectUri}));const company=await qboRequestJson<{CompanyInfo?:{CompanyName?:string;Id?:string}}>(realmId,environment,token.access_token,'/companyinfo/'+encodeURIComponent(realmId));if(company.CompanyInfo?.Id!==realmId||typeof company.CompanyInfo.CompanyName!=='string')throw new Error('QuickBooks company identity could not be verified.');const data={businessId:QBO_BUSINESS_ID,realmId,companyName:company.CompanyInfo.CompanyName,environment,scopes:token.scope||scopes,accessTokenCiphertext:encryptSecret(token.access_token,'qbo-access:'+realmId),refreshTokenCiphertext:encryptSecret(token.refresh_token,'qbo-refresh:'+realmId),accessTokenExpiresAt:new Date(Date.now()+token.expires_in*1000),refreshTokenExpiresAt:new Date(Date.now()+token.x_refresh_token_expires_in*1000),status:'CONNECTED',disconnectedAt:null};return prisma.qboConnection.upsert({where:{businessId:QBO_BUSINESS_ID},create:data,update:data});}
async function qboRequestJson<T>(realmId:string,environment:QboEnvironment,accessToken:string,path:string):Promise<T>{let response:Response;try{response=await fetch(apiBase(environment)+'/v3/company/'+encodeURIComponent(realmId)+path,{headers:{Authorization:'Bearer '+accessToken,Accept:'application/json'},cache:'no-store',redirect:'error',signal:AbortSignal.timeout(20000)});}catch{throw new Error('QuickBooks company verification request failed.');}if(!response.ok)throw new Error('QuickBooks company verification failed with status '+response.status+'.');return response.json() as Promise<T>;}
export async function consumeAuthorizationState(state:string,cookieValue:string){if(!state||state.length>128||!cookieValue||!secureEqual(state,cookieValue))throw new Error('QuickBooks authorization state did not match this browser session.');const stateHash=sha(state);return prisma.$transaction(async tx=>{const row=await tx.oAuthState.findUnique({where:{stateHash}});if(!row||row.expiresAt<=new Date())throw new Error('QuickBooks authorization state expired or was already used.');await tx.oAuthState.delete({where:{stateHash}});return row;});}
const refreshLocks=new Map<string,Promise<string>>();
export async function refreshConnection(connection:NonNullable<Awaited<ReturnType<typeof getConnection>>>){const existing=refreshLocks.get(connection.id);if(existing)return existing;const promise=(async()=>{if(connection.refreshTokenExpiresAt<=new Date()){await prisma.qboConnection.update({where:{id:connection.id},data:{status:'REAUTH_REQUIRED',lastSyncErrorCode:'REFRESH_EXPIRED'}});throw new Error('QuickBooks authorization expired; reconnect the account.');}const secret=decryptSecret(connection.refreshTokenCiphertext,'qbo-refresh:'+connection.realmId);let token:TokenResponse;try{token=await postToken(new URLSearchParams({grant_type:'refresh_token',refresh_token:secret}));}catch(e){await prisma.qboConnection.update({where:{id:connection.id},data:{status:'REAUTH_REQUIRED',lastSyncErrorCode:'TOKEN_REFRESH_REJECTED'}});throw e;}const next={accessTokenCiphertext:encryptSecret(token.access_token,'qbo-access:'+connection.realmId),refreshTokenCiphertext:encryptSecret(token.refresh_token,'qbo-refresh:'+connection.realmId),accessTokenExpiresAt:new Date(Date.now()+token.expires_in*1000),refreshTokenExpiresAt:new Date(Date.now()+token.x_refresh_token_expires_in*1000),status:'CONNECTED',lastSyncErrorCode:null};await prisma.qboConnection.update({where:{id:connection.id},data:next});return token.access_token;})();refreshLocks.set(connection.id,promise);try{return await promise;}finally{refreshLocks.delete(connection.id);}}
export async function getConnection(){return prisma.qboConnection.findUnique({where:{businessId:QBO_BUSINESS_ID}});}
export async function validAccessToken(){const connection=await getConnection();if(!connection||connection.status==='DISCONNECTED'||connection.disconnectedAt)throw new Error('QuickBooks is not connected.');if(connection.accessTokenExpiresAt.getTime()<Date.now()+60_000)return refreshConnection(connection);return decryptSecret(connection.accessTokenCiphertext,'qbo-access:'+connection.realmId);}
export async function qboFetch(path:string,query?:Record<string,string>){let connection=await getConnection();if(!connection)throw new Error('QuickBooks is not connected.');let token=await validAccessToken();const url=new URL(apiBase(connection.environment as QboEnvironment)+'/v3/company/'+encodeURIComponent(connection.realmId)+path);for(const [k,v] of Object.entries(query||{}))url.searchParams.set(k,v);for(let attempt=0;attempt<5;attempt++){let response:Response;try{response=await fetch(url,{headers:{Authorization:'Bearer '+token,Accept:'application/json'},cache:'no-store',redirect:'error',signal:AbortSignal.timeout(25000)});}catch{if(attempt<2){await new Promise(r=>setTimeout(r,250*2**attempt));continue;}throw new Error('QuickBooks API request failed or timed out.');}if(response.status===401&&attempt===0){connection=await getConnection();if(!connection)throw new Error('QuickBooks is disconnected.');token=await refreshConnection(connection);continue;}if(response.status===429){if(attempt===4)throw new Error('QuickBooks rate limit remains active after bounded retries.');const seconds=Number(response.headers.get('Retry-After')||'1');await new Promise(r=>setTimeout(r,Math.min(30,Math.max(1,seconds))*1000));continue;}if(response.status>=500&&attempt<3){await new Promise(r=>setTimeout(r,250*2**attempt));continue;}if(!response.ok)throw new Error('QuickBooks API request failed with status '+response.status+'.');return response.json();}throw new Error('QuickBooks API request failed after bounded retries.');}
export async function disconnectQuickBooks(){const connection=await getConnection();if(!connection)return {revoked:false};let revoked=false;let revokeError:string|undefined;if(connection.status!=='DISCONNECTED'&&connection.refreshTokenCiphertext){try{const cfg=qboConfig();const refreshToken=decryptSecret(connection.refreshTokenCiphertext,'qbo-refresh:'+connection.realmId);const response=await fetch(revokeEndpoint,{method:'POST',redirect:'error',headers:{Authorization:'Basic '+Buffer.from(cfg.clientId+':'+cfg.clientSecret).toString('base64'),'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({token:refreshToken}),cache:'no-store',signal:AbortSignal.timeout(15000)});revoked=response.ok;if(!response.ok)revokeError='Provider revocation returned status '+response.status+'.';}catch{revokeError='Provider revocation could not be confirmed.';}}await prisma.qboConnection.update({where:{id:connection.id},data:{status:'DISCONNECTED',disconnectedAt:new Date(),accessTokenCiphertext:'',refreshTokenCiphertext:'',lastSyncErrorCode:revokeError?'REVOCATION_UNCONFIRMED':'DISCONNECTED'}});return {revoked,revokeError};}
export function callbackCookieOptions(redirectUri:string){return {httpOnly:true as const,sameSite:'lax' as const,secure:new URL(redirectUri).protocol==='https:',path:'/api/integrations/qbo/callback',maxAge:600};}
