'use client';
import { useEffect, useState } from 'react';
import { providers } from '@/lib/integrations/catalog';
type Connection=typeof providers[number]&{status:string;snapshot?:any};
export default function IntegrationsPage(){
 const [csv,setCsv]=useState(''),[preview,setPreview]=useState<any>(null);
 const [connections,setConnections]=useState<Connection[]>([]),[qbo,setQbo]=useState<any>(null),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[automatic,setAutomatic]=useState(false);
 async function load(){const [r,q]=await Promise.all([fetch('/api/integrations',{cache:'no-store'}),fetch('/api/integrations/qbo/status',{cache:'no-store'})]);if(!r.ok||!q.ok)throw new Error('Unable to load connections.');setConnections((await r.json()).integrations);setQbo((await q.json()).connection);}
 useEffect(()=>{load().catch(()=>setMessage('Unable to load connections.'));},[]);
 async function sync(id:string){setBusy(id);setMessage('');try{const r=await fetch('/api/integrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Sync failed.');await load();setMessage('Records refreshed and evidence checks completed.');}catch(e){setMessage(e instanceof Error?e.message:'Sync failed.');}finally{setBusy('');}}
 useEffect(()=>{if(!automatic)return;const timer=setInterval(async()=>{for(const p of providers.filter(p=>p.adapter)){try{const r=await fetch('/api/integrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:p.id})});if(!r.ok){setMessage('Automatic refresh could not complete. Check provider credentials.');}}catch{setMessage('Automatic refresh failed.');}}load().catch(()=>setMessage('Unable to reload reports.'));},900000);return()=>clearInterval(timer);},[automatic]);
 async function parseCsv(){try{const r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csvContent:csv})});const d=await r.json();if(!r.ok)throw new Error(d.error||'CSV validation failed.');setPreview(d.result);}catch(e){setMessage(e instanceof Error?e.message:'CSV validation failed.');}}
 return <div className="space-y-6"><h1 className="text-2xl font-bold">Connections & evidence sync</h1><p className="text-slate-400">Implemented connectors can import verified financial records. After a sync or reviewed upload, choose the matching business in AI Analyst to request evidence-gated OpenAI analysis. OAuth connection by itself does not create financial evidence.</p><ol className="list-decimal pl-6 space-y-2"><li>Have your administrator authorize read access in the provider account.</li><li>Store the Intuit client ID, client secret and encryption key in this project's ignored local .env; never paste keys into this page.</li><li>Register the exact callback URI from BIZBETTER_QBO_REDIRECT_URI in your Intuit app settings, restart the local server, then choose Connect sandbox with OAuth.</li><li>Review evidence, resolve missing data, and assign recovery steps. Confirm any recovery against later statements.</li></ol><label className="flex gap-2"><input type="checkbox" checked={automatic} onChange={e=>setAutomatic(e.target.checked)}/>Refresh implemented connectors every 15 minutes while this page stays open</label><p className="text-sm text-slate-400">Refresh requires this page and the local server to remain open. Stripe has a read-only transaction adapter. QuickBooks OAuth is implemented, but QuickBooks financial sync is not yet implemented. Other listed providers may not have an adapter.</p>{message&&<p role="status" className="border border-amber-600 p-3">{message}</p>}
 <a href="/leaks" className="block text-emerald-400 underline">Open source-backed findings, confidence criteria and recovery guides</a><div className="grid md:grid-cols-2 gap-4">{connections.map(c=><section key={c.id} className="rounded-xl border border-slate-700 p-4 space-y-3"><h2 className="font-bold">{c.name}</h2><p>{c.category} · {c.status}</p><p className="text-sm text-slate-400">{c.setup}</p>{c.id==='qbo'?<a className="rounded bg-emerald-700 px-3 py-2" href="/api/integrations/qbo/connect">Connect sandbox with OAuth</a>:c.adapter&&<button disabled={!!busy} className="rounded bg-emerald-700 px-3 py-2 disabled:opacity-50" onClick={()=>sync(c.id)}>{busy===c.id?'Reading records…':'Sync verified records'}</button>}{c.snapshot&&<><a className="text-emerald-400 underline" href="/financials">Open normalized source records and evidence audit</a><a className="block text-emerald-400 underline" href="/analyst?businessId=local-workspace">Ask AI Analyst about this business</a><p className="text-sm">Last successful read: {c.snapshot.syncedAt} · {c.snapshot.records} records</p>{c.snapshot.reports.map((report:any,i:number)=><div key={i} className="space-y-3"><p>{report.evidence.currency} · {report.evidence.periodStart} to {report.evidence.periodEnd}</p><p className="text-sm">{report.analysis.coverage}</p>{report.analysis.findings.length===0&&<p>No supported loss finding in these records. This does not establish that the business has no leaks.</p>}{report.analysis.findings.map((f:any)=><article key={f.id} className="border-l-2 border-amber-500 pl-3"><h3 className="font-bold">{f.title} · {f.currency} {f.amount.toFixed(2)}</h3><p>{f.evidence}</p><h4 className="mt-2 font-semibold">Recovery guide</h4><ol className="list-decimal pl-5">{f.recovery.map((s:string)=><li key={s}>{s}</li>)}</ol><h4 className="mt-2 font-semibold">Prevention</h4><ul className="list-disc pl-5">{f.prevention.map((s:string)=><li key={s}>{s}</li>)}</ul></article>)}<details><summary>Data still needed to investigate further</summary><ul className="list-disc pl-5">{report.analysis.missingData.map((s:string)=><li key={s}>{s}</li>)}</ul></details></div>)}</>}</section>)}</div><section className="space-y-3"><h2 className="font-bold">CSV validation preview</h2><p>Preview only: this does not import or reconcile records into your books.</p><textarea aria-label="CSV records" className="w-full h-40 bg-slate-900 border border-slate-600 p-3" value={csv} onChange={e=>setCsv(e.target.value)}/><button className="rounded bg-slate-700 px-3 py-2" onClick={parseCsv}>Parse & validate CSV</button>{preview&&<pre className="overflow-auto whitespace-pre-wrap text-sm">{JSON.stringify(preview,null,2)}</pre>}</section></div>;
}
