import { NextRequest, NextResponse } from 'next/server';
import { createHash, randomUUID } from 'crypto';
import { assertLocal } from '@/lib/evidence/access';
import { appendRecords, workspace, BUSINESS_ID } from '@/lib/evidence/repository';
import { parseEvidenceCSV } from '@/lib/evidence/importer';
import { SourceRecord } from '@/lib/evidence/model';
export const dynamic='force-dynamic';export const runtime='nodejs';
export async function GET(req:NextRequest){try{assertLocal(req);return NextResponse.json(await workspace(req.nextUrl.searchParams.get('businessId')||BUSINESS_ID),{headers:{'Cache-Control':'no-store'}});}catch{return NextResponse.json({error:'Unable to read the local evidence workspace.'},{status:403});}}
export async function POST(req:NextRequest){try{assertLocal(req,true);if(Number(req.headers.get('content-length')||0)>2000000)throw new Error('Import size limit exceeded.');const body=await req.json();if(typeof body.csvContent==='string')body.records=parseEvidenceCSV(body.csvContent);if(!Array.isArray(body.records)||body.records.length>10000)throw new Error('Provide at most 10,000 normalized records.');const businessId=body.businessId||BUSINESS_ID;await workspace(businessId);const syncId=randomUUID(),importedAt=new Date().toISOString();const records:SourceRecord[]=body.records.map((r:SourceRecord)=>{if(r.environment&&r.environment!=='REAL')throw new Error('Demo records are prohibited.');return {id:createHash('sha256').update(JSON.stringify([businessId,r.sourceRecordId,r.metric,r.periodStart,r.periodEnd,r.value,r.currency,r.decimals,r.basis,r.entityId,r.complete])).digest('hex'),businessId,environment:'REAL',sourceSystem:'Owner-entered records',sourceRecordId:r.sourceRecordId,syncId,importedAt,metric:r.metric,value:r.value,currency:r.currency,decimals:r.decimals,basis:r.basis,entityId:r.entityId,periodStart:r.periodStart,periodEnd:r.periodEnd,complete:r.complete,verification:'OWNER_ENTERED'};});await appendRecords(records);return NextResponse.json(await workspace(businessId));}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Import rejected.'},{status:400});}}
