import assert from 'node:assert/strict';
import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { analyze, confidence, dataQuality, guardedNarrative, historicalTrend, correlateSeries, learnOutcomes, measuredResult, validateBenchmark, validateRecords } from '../lib/evidence/engine';
import { SourceRecord, Decision, INSUFFICIENT } from '../lib/evidence/model';
import { ProfitLeakEngine } from '../lib/engines/leak-engine';
import { OpportunityEngine } from '../lib/engines/opportunity-engine';
import { AIAnalystEngine } from '../lib/engines/ai-analyst';
import { CSVDataImporter } from '../lib/engines/csv-importer';
const businessId='local-workspace';
const fixture=(overrides:Partial<SourceRecord>={}):SourceRecord=>({id:randomUUID(),businessId,environment:'REAL',sourceSystem:'TEST Fixture',sourceRecordId:randomUUID(),syncId:'test-sync',periodStart:'2026-01-01',periodEnd:'2026-01-31',importedAt:new Date().toISOString(),metric:'net_profit',value:-12345,currency:'USD',decimals:2,basis:'accrual',complete:true,verification:'OWNER_ENTERED',...overrides});
let count=0;async function check(name:string,fn:()=>unknown){await fn();count++;console.log('PASS '+count+' '+name);}
async function main(){
 await check('Missing and partial data cannot create financial findings',()=>{assert.equal(analyze([],businessId).message,INSUFFICIENT);assert.equal(analyze([fixture({complete:false})],businessId).findings.length,0);assert.equal(dataQuality([]).score,null);});
 await check('Demo and cross-business records are rejected',()=>{assert.throws(()=>analyze([fixture({environment:'DEMO'})],businessId),/prohibited/);assert.throws(()=>analyze([fixture({businessId:'another'})],businessId),/prohibited/);});
 await check('Source calculations reproduce exactly in minor currency units',()=>{const r=fixture();const f=analyze([r],businessId).findings[0];assert.equal(f.impactMinor,-r.value);assert.deepEqual(f.inputs,{net_profit:r.value});assert.equal(f.formula,'max(0, -net_profit)');assert.equal(f.id,analyze([r],businessId).findings[0].id);});
 await check('Narrative cannot introduce unsupported dollar amounts, titles or evidence',()=>{const f=analyze([fixture()],businessId).findings;assert.equal(guardedNarrative([{findingId:f[0].id,title:f[0].title,impactMinor:f[0].impactMinor}],f).length,1);assert.throws(()=>guardedNarrative([{findingId:f[0].id,title:f[0].title,impactMinor:999999}],f),/Unsupported/);assert.throws(()=>guardedNarrative([{findingId:f[0].id,title:'Save $107,200',impactMinor:f[0].impactMinor}],f),/Unsupported/);assert.throws(()=>guardedNarrative([{findingId:'invented',title:'Fake',impactMinor:1}],f),/Unsupported/);});
 await check('Benchmarks require complete valid provenance',()=>{assert.throws(()=>validateBenchmark({value:29} as any),/requires/);assert.throws(()=>validateBenchmark({source:'https://example.test',publishedAt:'2026-02-30',industry:'HVAC',companySize:'small',geography:'US',metricDefinition:'margin',value:29}),/requires/);assert.equal(validateBenchmark({source:'https://example.test/report',publishedAt:'2026-01-01',industry:'TEST',companySize:'TEST',geography:'TEST',metricDefinition:'TEST',value:29}).value,29);});
 await check('Confidence derives from explicit, reproducible evidence criteria',()=>{const r=fixture();const c=confidence([r]);assert.equal(c.level,'MEDIUM');assert.equal(c.criteria.providerVerified,false);assert.equal(confidence([{...r,complete:false}]).level,'LOW');assert.deepEqual(c,confidence([r]));assert.ok(c.explanation.length>=5);});
 await check('Every finding has a traceable evidence chain',()=>{const r=fixture(),f=analyze([r],businessId).findings[0];assert.deepEqual(f.sourceRecordIds,[r.id]);assert.deepEqual(f.syncIds,[r.syncId]);assert.deepEqual(f.sourceSystems,[r.sourceSystem]);assert.ok(f.engineVersion&&f.createdAt&&f.formula);assert.throws(()=>validateRecords([fixture({sourceRecordId:''})],businessId),/provenance/);});
 await check('Cross-system discrepancies require matching currency, periods and definitions',()=>{const a=fixture({sourceSystem:'TEST Books',metric:'revenue',value:10000}),b=fixture({sourceSystem:'TEST Operations',metric:'revenue',value:9000});assert.equal(analyze([a,b],businessId).findings[0].impactMinor,1000);assert.equal(analyze([a,{...b,currency:'EUR'}],businessId).findings.length,0);assert.equal(analyze([a,{...b,basis:'cash'}],businessId).findings.length,0);assert.equal(analyze([a,{...b,periodEnd:'2026-01-30'}],businessId).findings.length,0);});
 await check('Realized results require comparable completed before/after evidence',()=>{const a=fixture({metric:'labor_cost',value:810000}),b=fixture({metric:'labor_cost',value:590000,periodStart:'2026-03-01',periodEnd:'2026-03-31'});const review=Object.fromEntries(['revenue','jobVolume','seasonality','employeeCount','hoursWorked','serviceMix','pricing','materialPrices','marketingVolume','oneTimeExpenses','otherChanges'].map(k=>[k,'Test fixture: comparable and reviewed.']));const d:Decision={id:'test-decision',findingId:'test-finding',businessId,decision:'ACCEPTED',owner:'TEST Owner',notes:'TEST implementation',createdAt:new Date().toISOString(),implementationDate:'2026-02-01',baselineIds:[a.id],afterIds:[b.id],confounderReview:review};assert.equal(measuredResult(d,[a,b],businessId).impactMinor,220000);assert.throws(()=>measuredResult({...d,implementationDate:undefined},[a,b],businessId),/Implementation/);assert.throws(()=>measuredResult({...d,confounderReview:{}},[a,b],businessId),/confounding/);assert.throws(()=>measuredResult(d,[a,{...b,currency:'EUR'}],businessId),/Non-comparable/);assert.throws(()=>measuredResult(d,[a],businessId),/pair/);});
 await check('Duplicate records, invalid dates and invalid values fail safely',()=>{const r=fixture();assert.throws(()=>analyze([r,r],businessId),/duplicate/);const duplicate={...r,id:randomUUID()};assert.equal(analyze([r,duplicate],businessId).findings.length,0);assert.equal(dataQuality([r,duplicate]).duplicateCount,1);assert.throws(()=>validateRecords([fixture({periodStart:'2026-02-30'})],businessId),/period/);assert.throws(()=>validateRecords([fixture({value:NaN})],businessId),/Invalid metric/);});
 await check('Missing job costs and processing fees cannot become assumed savings',()=>{const rev=fixture({metric:'job_revenue',value:10000,entityId:'job1'});assert.equal(analyze([rev],businessId).findings.length,0);const fees=analyze([fixture({metric:'fees',value:100})],businessId).findings[0];assert.equal(fees.opportunity,false);assert.equal(fees.classification,'FACT');});
 await check('Historical statistics reject insufficient and gapped data',()=>{assert.equal(historicalTrend([fixture()]).message,INSUFFICIENT);const rows=Array.from({length:12},(_,i)=>fixture({metric:'revenue',value:1000+i*100,periodStart:new Date(Date.UTC(2025,i,1)).toISOString().slice(0,10),periodEnd:new Date(Date.UTC(2025,i+1,0)).toISOString().slice(0,10)}));const trend=historicalTrend(rows);assert.equal(trend.slopeMinorPerMonth,100);assert.equal(trend.rSquared,1);assert.equal(historicalTrend(rows.filter((_,i)=>i!==4)).message,INSUFFICIENT);const second=rows.map(r=>({...r,id:randomUUID(),sourceRecordId:randomUUID(),metric:'labor_cost' as const,value:r.value*2}));assert.equal(correlateSeries(rows,second).coefficient,1);});
 await check('Legacy unsupported analytics are unavailable in production',()=>{assert.throws(()=>new ProfitLeakEngine().evaluate({}),/prohibited/);assert.throws(()=>new OpportunityEngine().evaluate({}),/prohibited/);assert.throws(()=>AIAnalystEngine.analyze('x',{}),/prohibited/);});
 await check('CSV parser never guesses missing dates, amounts or categories',()=>{const result=CSVDataImporter.parseTransactionsCSV('Date,Category,Description,Amount\n,LABOR,Cost,10\n2026-01-01,UNKNOWN,Cost,10\n2026-01-01,LABOR,Cost,');assert.equal(result.success,false);assert.equal(result.transactions.length,0);assert.equal(result.totalExpenses,null);});
 // Repository tests use a fresh temporary workspace; never write fixtures into the real app.
 const previous=process.cwd();const dir=await mkdtemp(path.join(tmpdir(),'bizbetter-integrity-test-'));process.chdir(dir);const repo=await import('../lib/evidence/repository');
 await check('Potential cannot skip validation or become realized by status alone',async()=>{await assert.rejects(repo.changeStage({findingId:'invented',state:'REALIZED'}),/not a quantified/);const paid=fixture({metric:'invoice_paid',value:25000,entityId:'invoice1'}),contract=fixture({metric:'invoice_contract',value:20000,entityId:'invoice1'});await repo.appendRecords([paid,contract]);const f=(await repo.workspace()).findings.find(f=>f.opportunity)!;await repo.changeStage({findingId:f.id,state:'POTENTIAL'});await assert.rejects(repo.changeStage({findingId:f.id,state:'REALIZED'}),/sequential/);await assert.rejects(repo.changeStage({findingId:f.id,state:'VALIDATED',validatedBy:'TEST'}),/reconciliation/);await repo.changeStage({findingId:f.id,state:'VALIDATED',validatedBy:'TEST',validationNotes:'TEST invoice and change orders checked.'});await assert.rejects(repo.changeStage({findingId:f.id,state:'IMPLEMENTED',implementationDate:'2026-02-01'}),/decision/);const d=await repo.recordDecision({findingId:f.id,decision:'ACCEPTED',owner:'TEST',notes:'TEST recovery action.'});await repo.changeStage({findingId:f.id,state:'IMPLEMENTED',decisionId:d.id,implementationDate:'2026-02-01'});await assert.rejects(repo.changeStage({findingId:f.id,state:'REALIZED'}),/Baseline/);assert.equal((await repo.workspace()).ledger[0].state,'IMPLEMENTED');});
 await check('Persistence and audit chain survive reads without fabricated outcomes',async()=>{const w=await repo.workspace();assert.equal(w.decisions.length,1);assert.ok(w.audit.length>=4);assert.equal(w.ledger[0].result,undefined);const file=JSON.parse(await readFile(path.join(dir,'.bizbetter-data/evidence-v1.json'),'utf8'));assert.equal(file.businessId,businessId);assert.equal(file.records.length,2);});
 await check('Realized opportunity recovery is linked to its original invoice evidence',async()=>{const w=await repo.workspace(),f=w.findings.find(f=>f.opportunity)!,d=w.decisions[0],paid=w.records.find(r=>r.metric==='invoice_paid')!;const after=fixture({metric:'invoice_paid',value:20000,entityId:'invoice1',periodStart:'2026-03-01',periodEnd:'2026-03-31'});await repo.appendRecords([after]);const review=Object.fromEntries(['revenue','jobVolume','seasonality','employeeCount','hoursWorked','serviceMix','pricing','materialPrices','marketingVolume','oneTimeExpenses','otherChanges'].map(k=>[k,'TEST comparable and reviewed.']));await assert.rejects(repo.changeStage({findingId:f.id,state:'REALIZED',baselineIds:[after.id],afterIds:[paid.id],confounderReview:review}),/Baseline/);const item=await repo.changeStage({findingId:f.id,state:'REALIZED',baselineIds:[paid.id],afterIds:[after.id],confounderReview:review});assert.equal(item.result?.impactMinor,5000);assert.equal(item.result?.classification,'REALIZED RESULT');assert.ok(item.result?.contradictions.some(s=>s.includes('counterfactual')));assert.equal((await repo.workspace()).decisions.find(r=>r.id===d.id)?.afterIds[0],after.id);});
 await check('Outcome learning stays insufficient without repeated revalidated outcomes',async()=>{const w=await repo.workspace();assert.equal(learnOutcomes(w.records,w.decisions,w.ledger).message,INSUFFICIENT);assert.equal(learnOutcomes([],[],[]).patterns.length,0);});
 process.chdir(previous);console.log('ALL '+count+' FINANCIAL INTEGRITY CHECKS PASSED. Fixtures remained in an isolated temporary workspace.');
}main().catch(e=>{console.error(e);process.exitCode=1;});
