import assert from 'node:assert/strict';
import { mkdtemp,rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import ExcelJS from 'exceljs';
import { parseCsv,parseXlsx,suggestMappings } from '../lib/intake/interpreter';
import { normalizeSheet } from '../lib/intake/normalize';
import { capabilityReport } from '../lib/intake/capabilities';
import { analyze } from '../lib/evidence/engine';

async function main(){
const goodCsv=`Job #,Completed Date,Tech,Invoice Total,Labor Cost,Material Cost,Callback
HV-001,2026-01-10,Alex,100,45,70,No
HV-002,2026-02-10,Sam,500,120,130,No
HV-003,2026-03-10,Alex,700,150,200,No
HV-004,2026-04-10,Lee,800,170,240,No
HV-005,2026-05-10,Sam,900,200,270,No`;
const sheet=parseCsv(goodCsv,'completed jobs export.csv')[0];
const result=normalizeSheet({businessId:'workspace-A',importId:'10000000-0000-4000-8000-000000000001',fileName:'completed jobs export.csv',fileType:'csv',sheet,mappings:sheet.mappings,currency:'USD',complete:true,basis:'accrual',sourceSystem:'Manual upload',existing:[]});
assert.equal(sheet.classification,'jobs');assert.equal(result.normalized.length,5);assert.equal(result.records.length,15);assert.equal(result.normalized[0].sourceFile,'completed jobs export.csv');assert.equal(result.normalized[0].sourceRow,2);assert.equal(result.normalized[0].normalizedValues.job_id,'HV-001');
const analysis=analyze(result.records,'workspace-A');assert(analysis.findings.some(f=>f.title.includes('HV-001')),'complete costs below revenue should not invent a loss');
const caps=capabilityReport(result.normalized,result.records);assert.equal(caps.analyses.find(a=>a.id==='job-profitability')?.status,'AVAILABLE');
const changedSheet=parseCsv(goodCsv.replace('70,No','90,No'),'completed jobs export.csv')[0];const changed=normalizeSheet({businessId:'workspace-A',importId:'10000000-0000-4000-8000-000000000002',fileName:'completed jobs export.csv',fileType:'csv',sheet:changedSheet,mappings:changedSheet.mappings,currency:'USD',complete:true,basis:'accrual',sourceSystem:'Manual upload',existing:[]});assert.notEqual(changed.records[2].id,result.records[2].id);assert.notDeepEqual(analyze(changed.records,'workspace-A').findings.map(f=>f.impactMinor),analysis.findings.map(f=>f.impactMinor));
const repeat=normalizeSheet({businessId:'workspace-A',importId:'10000000-0000-4000-8000-000000000003',fileName:'overlap.csv',fileType:'csv',sheet,mappings:sheet.mappings,currency:'USD',complete:true,basis:'accrual',sourceSystem:'Manual upload',existing:result.normalized});assert.equal(repeat.duplicateCount,5);assert(repeat.normalized.every(r=>r.quality==='POSSIBLE_DUPLICATE'));assert.equal(analyze(repeat.records.filter(r=>!repeat.normalized.some(n=>n.quality!=='ACCEPTED'&&n.id===r.normalizedRecordId)),'workspace-A').findings.length,0);
const unclear=suggestMappings(['Amount'],'generic')[0];assert(unclear.confidence<.85&&!unclear.confirmed);assert.throws(()=>normalizeSheet({businessId:'workspace-A',importId:'10000000-0000-4000-8000-000000000004',fileName:'x.csv',fileType:'csv',sheet:{...sheet,headers:['Amount'],rows:[{Amount:'500'}]},mappings:[unclear],currency:'USD',complete:true,existing:[]}),/explicit human confirmation/);
const incompleteSheet=parseCsv('Transaction ID,Vendor,Amount,Description\nT-1,North Supply,850.00,Parts purchase\nT-2,North Supply,640.00,Filter purchase','unfamiliar supplier export.csv')[0];const amount=incompleteSheet.mappings.find(m=>m.sourceColumn==='Amount')!;const incomplete=normalizeSheet({businessId:'workspace-A',importId:'10000000-0000-4000-8000-000000000005',fileName:'unfamiliar supplier export.csv',fileType:'csv',sheet:incompleteSheet,mappings:incompleteSheet.mappings.map(m=>m===amount?{...m,targetField:'vendor_spend',confidence:1,confirmed:true}:m),currency:'',complete:false,existing:[]});assert.equal(incomplete.records.length,0);assert.equal(analyze(incomplete.records,'workspace-A').findings.length,0);assert.equal(capabilityReport(incomplete.normalized,incomplete.records).analyses.find(a=>a.id==='vendor-concentration')?.status,'PARTIALLY AVAILABLE');assert(incomplete.normalized.every(r=>r.normalizedValues.date===undefined));
assert.throws(()=>parseCsv('a,b\n"broken,x'),/Unclosed quoted/);assert.equal(parseCsv('a,b\n=2+2,1')[0].rows[0].a,'=2+2'); // formula-like CSV text remains inert and is never evaluated
const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Jobs');ws.addRow(['Job #','Revenue']);ws.addRow(['J-1',100]);const xlsx=Buffer.from(await wb.xlsx.writeBuffer());const parsed=await parseXlsx(xlsx,'jobs.xlsx');assert.equal(parsed[0].rows.length,1);await assert.rejects(()=>parseXlsx(Buffer.from('not an xlsx'),'bad.xlsx'),/ZIP signature/);const formulaBook=new ExcelJS.Workbook(),formulaSheet=formulaBook.addWorksheet('Formula');formulaSheet.addRow(['Revenue']);formulaSheet.addRow([{formula:'1+1',result:2}]);const formula=Buffer.from(await formulaBook.xlsx.writeBuffer());await assert.rejects(()=>parseXlsx(formula,'formula.xlsx'),/Formula cells/);
const testDir=await mkdtemp(path.join(os.tmpdir(),'bizbetter-intake-')),oldCwd=process.cwd();try{process.chdir(testDir);const repo=await import('../lib/evidence/repository');const a=await repo.createBusiness('Consultant client A'),b=await repo.createBusiness('Consultant client B');const importId='10000000-0000-4000-8000-000000000006',normalized=normalizeSheet({businessId:a.id,importId,fileName:'jobs.csv',fileType:'csv',sheet,mappings:sheet.mappings,currency:'USD',complete:true,existing:[]});const batch={id:importId,businessId:a.id,fileName:'jobs.csv',fileType:'csv' as const,datasetType:'jobs' as const,sourceSystem:'Manual upload',status:'COMMITTED' as const,rowCount:5,acceptedCount:5,duplicateCount:0,invalidCount:0,sourceDigest:'d'.repeat(64),mappingVersion:'test',mappings:sheet.mappings,createdAt:new Date().toISOString(),warnings:[]};await repo.commitIntake({batch,normalized:normalized.normalized,records:normalized.records});assert.equal((await repo.intakeWorkspace(a.id)).analysis.findings.length,1);assert.equal((await repo.intakeWorkspace(b.id)).normalized.length,0);assert.equal((await repo.intakeWorkspace(repo.BUSINESS_ID)).normalized.length,0);await assert.rejects(()=>repo.appendRecords([{...normalized.records[0],id:'demo-record',environment:'DEMO'}]),/Demo or different-business/);await repo.rejectImport(importId,a.id);assert.equal((await repo.intakeWorkspace(a.id)).sourceRecords.length,0);assert.equal((await repo.intakeWorkspace(a.id)).analysis.findings.length,0);console.log('PASS business isolation, demo isolation, import rejection rollback and audit-backed persistence');}finally{process.chdir(oldCwd);await rm(testDir,{recursive:true,force:true});}
console.log('PASS CSV/XLSX parsing, formula rejection, mapping confirmation, provenance, exact duplicates, evidence-derived findings, changed-value propagation, insufficient data, and analysis unlocks');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
