import type { NormalizedBusinessRecord, SourceRecord } from '@/lib/evidence/model';

type Rule={id:string;name:string;category:string;required:string[];optional:string[];minMonths:number;minSample:number;importance:number;howTo:string;joinKey?:string};
export const ANALYSIS_RULES:Rule[]=[
 {id:'revenue-trend',name:'Revenue trend',category:'Financial',required:['revenue','date'],optional:['customer','job_id','marketing_source'],minMonths:8,minSample:8,importance:10,howTo:'Export dated sales or transaction details with the reporting period and amount.'},
 {id:'expense-category-drift',name:'Expense category review',category:'Financial',required:['expense','category','date'],optional:['vendor'],minMonths:3,minSample:3,importance:9,howTo:'Export dated expense or general-ledger rows with account/category and signed amount.'},
 {id:'vendor-concentration',name:'Vendor concentration',category:'Vendors',required:['vendor','expense'],optional:['date','account'],minMonths:0,minSample:5,importance:7,joinKey:'vendor',howTo:'Export bills or transaction detail with vendor name and amount.'},
 {id:'job-profitability',name:'Job profitability',category:'Jobs',required:['job_id','revenue','labor_cost','material_cost','date'],optional:['job_type'],minMonths:0,minSample:5,importance:10,joinKey:'job_id',howTo:'Export completed jobs with job ID, revenue, actual labor cost and direct material cost.'},
 {id:'technician-profitability',name:'Technician contribution',category:'Labor',required:['job_id','technician','revenue','labor_cost','date'],optional:['labor_hours','material_cost','job_type'],minMonths:0,minSample:10,importance:10,joinKey:'job_id',howTo:'Provide job revenue matched to technician-attributed time and actual loaded labor cost.'},
 {id:'labor-utilization',name:'Labor utilization',category:'Labor',required:['employee','labor_hours','date'],optional:['overtime_hours','job_id'],minMonths:1,minSample:10,importance:8,howTo:'Export employee time entries with regular/overtime hours and dates; job attribution improves this analysis.'},
 {id:'callback-economics',name:'Callback economics',category:'Operational',required:['job_id','callback_indicator','labor_cost','date'],optional:['material_cost','labor_hours'],minMonths:0,minSample:5,importance:7,joinKey:'job_id',howTo:'Provide callback/rework flags linked to the original job and the actual rework time/material cost.'},
 {id:'marketing-roi',name:'Marketing return',category:'Marketing',required:['marketing_spend','marketing_source','revenue'],optional:['customer','job_id','date'],minMonths:3,minSample:10,importance:8,joinKey:'customer',howTo:'Match dated campaign/source spend to leads and collected or invoiced revenue with an attribution key.'},
 {id:'receivables-aging',name:'Receivables follow-up',category:'Receivables',required:['invoice_id','revenue','due_date','amount_paid'],optional:['customer','date'],minMonths:0,minSample:1,importance:9,joinKey:'invoice_id',howTo:'Provide invoice IDs, due dates, original amounts and payment status/amounts.'},
 {id:'payroll-overtime',name:'Overtime decomposition',category:'Payroll',required:['employee','overtime_hours','labor_cost','date'],optional:['job_id','labor_hours'],minMonths:3,minSample:10,importance:8,joinKey:'employee',howTo:'Export payroll detail with employee, regular/overtime hours, gross wages and employer cost.'},
];
const fields=(rows:NormalizedBusinessRecord[])=>{const set=new Set(rows.filter(r=>r.quality==='ACCEPTED').flatMap(r=>Object.entries(r.normalizedValues).filter(([,v])=>v!==null&&v!=='').map(([k])=>k)));if(set.has('vendor_spend')||set.has('expenses'))set.add('expense');if(set.has('marketing_spend'))set.add('marketing_spend');return set;};
export function capabilityReport(normalized:NormalizedBusinessRecord[],records:SourceRecord[],imports:Array<{id:string;mappings?:Array<{confidence:number;confirmed:boolean}>}>=[]){const present=fields(normalized);const analyses=ANALYSIS_RULES.map(rule=>{const missing=rule.required.filter(x=>!present.has(x));const acceptedRows=normalized.filter(r=>r.quality==='ACCEPTED');let sourceRows:NormalizedBusinessRecord[];if(rule.joinKey){const groups=new Map<string,NormalizedBusinessRecord[]>();for(const r of acceptedRows){const key=r.normalizedValues[rule.joinKey];if(typeof key!=='string'||!key.trim())continue;const joinDate=rule.required.includes('date')?String(r.normalizedValues.date||''):'';if(rule.required.includes('date')&&!joinDate)continue;const groupKey=key+'|'+joinDate;groups.set(groupKey,[...(groups.get(groupKey)||[]),r]);}sourceRows=Array.from(groups.values()).filter(group=>rule.required.every(f=>group.some(r=>r.normalizedValues[f]!==undefined&&r.normalizedValues[f]!==null&&r.normalizedValues[f]!==''))).flat();}else sourceRows=acceptedRows.filter(r=>rule.required.every(f=>r.normalizedValues[f]!==undefined&&r.normalizedValues[f]!==null&&r.normalizedValues[f]!==''));const months=new Set(sourceRows.map(r=>String(r.normalizedValues.date||'').slice(0,7)).filter(x=>/^\d{4}-\d{2}$/.test(x))).size;const sample=rule.joinKey?new Set(sourceRows.map(r=>r.normalizedValues[rule.joinKey!])).size:sourceRows.length;const historicalMissing=rule.minMonths>0&&months<rule.minMonths;const sampleMissing=sample<rule.minSample;const datasetExists=normalized.some(r=>r.quality==='ACCEPTED');let status:'AVAILABLE'|'PARTIALLY AVAILABLE'|'BLOCKED';const engineReady=['revenue-trend','job-profitability'].includes(rule.id);if(!missing.length&&!historicalMissing&&!sampleMissing&&engineReady)status='AVAILABLE';else if(datasetExists&&rule.required.some(f=>present.has(f))&&(!missing.length||missing.length<rule.required.length))status='PARTIALLY AVAILABLE';else status='BLOCKED';return {...rule,status,missing:[...missing,...(!engineReady&&datasetExists?['Data is retained and mapped, but a validated analysis engine is not implemented yet.']:[]),...(historicalMissing?[`More history required: ${months}/${rule.minMonths} distinct months.`]:[]),...(sampleMissing?[`More matched records required: ${sample}/${rule.minSample}.`]:[])],matchedRecords:sample,observedMonths:months,sourceTypes:Array.from(new Set(normalized.filter(r=>r.quality==='ACCEPTED').map(r=>r.datasetType))).filter(Boolean)};});
 const categories=['Financial','Jobs','Labor','Payroll','Customers','Vendors','Materials','Marketing','Receivables','Operational','Pricing'];const coverage=categories.map(category=>{const rules=analyses.filter(a=>a.category===category),available=rules.filter(a=>a.status==='AVAILABLE').length,partial=rules.filter(a=>a.status==='PARTIALLY AVAILABLE').length,count=normalized.filter(r=>r.quality==='ACCEPTED'&&categoryTypes[category]?.includes(r.datasetType)).length;const stale=normalized.some(r=>r.quality==='ACCEPTED'&&categoryTypes[category]?.includes(r.datasetType)&&typeof r.normalizedValues.date==='string'&&Date.now()-Date.parse(r.normalizedValues.date)>90*86400000);const status: 'Available'|'Partial'|'Stale'|'Missing'=stale?'Stale':available?'Available':partial?'Partial':count?'Partial':'Missing';const problems=normalized.filter(r=>r.quality!=='ACCEPTED'&&categoryTypes[category]?.includes(r.datasetType)).length;return {category,status,records:count,qualityIssues:problems,explanation:rules.length?rules.map(a=>`${a.name}: ${a.status}${a.missing.length?'; '+a.missing.join(', '):''}`).join(' | '):count?'Records received; no registered analysis uses them yet.':'No dataset received.'};});
 const effort:Record<string,number>={Financial:1,Jobs:3,Labor:4,Payroll:3,Vendors:2,Marketing:4,Receivables:2,Operational:3,Customers:3,Materials:2,Pricing:2};const recommendations=analyses.filter(a=>a.status!=='AVAILABLE').map(a=>{const unlocks=analyses.filter(other=>other.id!==a.id&&other.status!=='AVAILABLE'&&other.required.some(f=>a.required.includes(f))).length;const alreadyPresent=a.required.filter(f=>present.has(f)).length;const priorityScore=a.importance*100+unlocks*15+alreadyPresent*4-a.missing.length*5-(effort[a.category]||3)*10;return {...a,unlocksByDataset:unlocks,priorityScore,effortCost:effort[a.category]||3};});
 return {analyses,coverage,recommendations:recommendations.sort((a,b)=>b.priorityScore-a.priorityScore||a.id.localeCompare(b.id)).slice(0,5),quality:qualityReport(normalized,records,imports),checklist:{received:Array.from(new Set(normalized.filter(r=>r.quality==='ACCEPTED').map(r=>r.datasetType))),recommended:analyses.filter(a=>a.status!=='AVAILABLE'&&a.importance>=8).map(a=>({dataset:a.category,name:a.name,unlocks:a.name,howTo:a.howTo})),optional:analyses.filter(a=>a.status!=='AVAILABLE'&&a.importance<8).map(a=>({dataset:a.category,name:a.name,unlocks:a.name,howTo:a.howTo}))}};}
const categoryTypes:Record<string,string[]>={Financial:['profit_and_loss','balance_sheet','general_ledger','transactions','invoices','payments','expenses','bills'],Jobs:['jobs','estimates','callbacks'],Labor:['technicians','time_entries','payroll'],Payroll:['payroll'],Customers:['customers','invoices','jobs'],Vendors:['vendors','bills','transactions','expenses'],Materials:['materials','inventory','jobs'],Marketing:['marketing','lead_sources','advertising'],Receivables:['invoices','payments'],Operational:['jobs','callbacks','time_entries','inventory'],Pricing:['estimates','invoices','jobs']};
export function qualityReport(normalized:NormalizedBusinessRecord[],records:SourceRecord[],imports:Array<{id:string;mappings?:Array<{confidence:number;confirmed:boolean}>}>=[]){const n=normalized.filter(r=>r.quality==='ACCEPTED'),criteria={completeness:{pass:n.length>0&&n.every(r=>r.sourceComplete),detail:'Owner-confirmed source completeness. Missing fields are still never filled.'},history:{pass:n.length>0&&new Set(n.map(r=>String(r.normalizedValues.date||'').slice(0,7))).size>=3,detail:'At least three observed calendar months, measured from source dates.'},mapping:{pass:n.length>0&&n.every(r=>r.mappingVersion===n[0].mappingVersion)&&imports.filter(i=>n.some(r=>r.importId===i.id)).every(i=>(i.mappings||[]).every(m=>m.confidence>=.85||m.confirmed)),detail:'Mapping version, source-to-field mapping, confidence and owner confirmation are retained.'},duplicateRisk:{pass:!normalized.some(r=>r.quality==='POSSIBLE_DUPLICATE'),detail:`${normalized.filter(r=>r.quality==='POSSIBLE_DUPLICATE').length} possible duplicates require review.`},freshness:{pass:n.length>0&&n.every(r=>typeof r.normalizedValues.date==='string'&&Date.now()-Date.parse(r.normalizedValues.date)<=90*86400000),detail:'Freshness is based on source-record dates, not upload time.'},relationships:{pass:n.some(r=>Boolean(r.normalizedValues.job_id||r.normalizedValues.invoice_id)),detail:'Stable job/invoice IDs are retained when present; fuzzy matches are never asserted.'},recordConsistency:{pass:records.every(r=>Number.isSafeInteger(r.value)),detail:'Financial values must be integer minor units.'}};const yes=Object.values(criteria).filter(c=>c.pass).length;return {status:n.length?'ASSESSED':'INSUFFICIENT DATA',score:n.length?Math.round(100*yes/Object.keys(criteria).length):null,formula:'Equal-weight count of 7 explicit checks; not an accounting accuracy score.',criteria,limitations:['Quality scoring does not verify source completeness or accounting correctness.','A partial export may contain internally consistent rows.','A numeric score is withheld when there are no accepted normalized records.']};}
