import { createHash,randomUUID } from 'crypto';
import type { DatasetType,Metric,NormalizedBusinessRecord,SourceRecord } from '@/lib/evidence/model';
import type { ColumnMapping,ParsedSheet } from './interpreter';
import { digestRows,MAPPING_VERSION,parseDate } from './interpreter';

const fields=new Set(['ignore','date','due_date','amount','revenue','net_profit','expense','expenses','vendor_spend','labor_cost','labor_hours','overtime_hours','material_cost','job_id','technician','employee','customer','vendor','invoice_id','transaction_id','account','category','marketing_source','marketing_spend','callback_indicator','estimate_outcome','job_type','service_type','regular_hours','gross_wages','employer_cost','campaign','geography','quantity','unit_cost','description','currency','payment_amount','amount_paid']);
const precision:Record<string,number>={USD:2,CAD:2,AUD:2,EUR:2,GBP:2,NZD:2,CHF:2,JPY:0,KRW:0,CLP:0};
function amountMinor(v:unknown,decimals:number):number|null {if(typeof v!=='string'&&typeof v!=='number')return null;let s=String(v).trim();if(!s||/[=+@]/.test(s[0]))return null;const neg=/^\(.*\)$/.test(s);if(neg)s=s.slice(1,-1);s=s.replace(/[$,\s]/g,'');if(!/^-?\d+(\.\d+)?$/.test(s))return null;const [,fraction='']=s.split('.');if(fraction.length>decimals)return null;const sign=(s.startsWith('-')?-1:1)*(neg?-1:1);const unsigned=s.replace(/^-/,''),[whole,part='']=unsigned.split('.');const minor=sign*Number(whole+part.padEnd(decimals,'0'));return Number.isSafeInteger(minor)?minor:null;}
function metric(field:string,dataset:DatasetType):Metric|null{if(field==='revenue')return dataset==='jobs'?'job_revenue':'revenue';if(field==='net_profit')return 'net_profit';if(field==='expenses'||field==='expense')return 'expenses';if(field==='vendor_spend')return 'vendor_spend';if(field==='labor_cost')return dataset==='jobs'?'job_labor':'labor_cost';if(field==='material_cost')return 'job_materials';if(field==='marketing_spend')return 'marketing_cost';if(field==='payment_amount'||field==='amount_paid')return 'invoice_paid';if(field==='receivable')return 'receivable';return null;}
export function normalizeSheet(input:{businessId:string;importId:string;fileName:string;fileType:'csv'|'xlsx'|'manual';sheet:ParsedSheet;mappings:ColumnMapping[];currency:string;complete:boolean;basis?:string;sourceSystem?:string;existing:NormalizedBusinessRecord[]}):{normalized:NormalizedBusinessRecord[];records:SourceRecord[];invalidCount:number;duplicateCount:number;warnings:string[]}{
 const {businessId,importId,sheet,mappings}=input;if(mappings.some(m=>!sheet.headers.includes(m.sourceColumn)||!fields.has(m.targetField)))throw new Error('Mapping refers to an unavailable source column or unsupported field.');const used=mappings.filter(m=>m.targetField!=='ignore').map(m=>m.targetField);if(new Set(used).size!==used.length)throw new Error('Each normalized field can be mapped from only one column per sheet.');if(mappings.some(m=>m.targetField!=='ignore'&&m.confidence<.85&&!m.confirmed))throw new Error('Low-confidence mappings need explicit human confirmation.');
 const timestamp=new Date().toISOString(),sourceSystem=input.sourceSystem?.trim()||'Manual upload',warnings:string[]=[],normalized:NormalizedBusinessRecord[]=[],records:SourceRecord[]=[];let invalidCount=0,duplicateCount=0;const seen:NormalizedBusinessRecord[]=[];
 const amountMappings=mappings.filter(m=>['revenue','net_profit','expense','expenses','vendor_spend','labor_cost','material_cost','marketing_spend','payment_amount','amount_paid'].includes(m.targetField));
 for(let i=0;i<sheet.rows.length;i++){const original=sheet.rows[i],mapped:Record<string,string|number|boolean|null>={};for(const m of mappings){if(m.targetField==='ignore')continue;const raw=original[m.sourceColumn];if(raw===null||raw==='')continue;if(m.targetField==='date'||m.targetField==='due_date'){mapped[m.targetField]=parseDate(raw);continue;}if(['amount','revenue','net_profit','expense','expenses','vendor_spend','labor_cost','material_cost','marketing_spend','payment_amount','amount_paid','regular_hours','labor_hours','overtime_hours','gross_wages','employer_cost','quantity','unit_cost'].includes(m.targetField)){let numberText=String(raw).trim();const parens=/^\(.*\)$/.test(numberText);if(parens)numberText=numberText.slice(1,-1);numberText=numberText.replace(/[$,\s]/g,'');const n=Number(numberText)*(parens?-1:1);if(Number.isFinite(n))mapped[m.targetField]=n;else {mapped[m.targetField]=null;warnings.push(`Row ${i+2}: ${m.sourceColumn} is not a readable number.`);}continue;}if(m.targetField==='callback_indicator'){const v=String(raw).trim().toLowerCase();if(['true','yes','y','1','callback','rework'].includes(v))mapped[m.targetField]=true;else if(['false','no','n','0','none'].includes(v))mapped[m.targetField]=false;else{mapped[m.targetField]=null;warnings.push(`Row ${i+2}: callback value needs a recognized explicit yes/no value.`);}continue;}mapped[m.targetField]=typeof raw==='string'?raw.trim():raw;}
  const identifier=String(mapped.transaction_id||mapped.invoice_id||mapped.job_id||'').trim()||undefined;const normalizedId=createHash('sha256').update(JSON.stringify([businessId,importId,sheet.name,i+2])).digest('hex');let quality:NormalizedBusinessRecord['quality']='ACCEPTED';let duplicateOf:string|undefined;const fingerprint=createHash('sha256').update(JSON.stringify([sheet.classification,mapped.date,mapped.invoice_id,mapped.transaction_id,mapped.job_id,mapped.vendor,mapped.customer,mapped.revenue,mapped.net_profit,mapped.expense,mapped.vendor_spend,mapped.labor_cost,mapped.material_cost])).digest('hex');if(identifier||mapped.date){const stableId=String(mapped.transaction_id||mapped.invoice_id||'').trim();const pool=[...input.existing,...seen];const dup=pool.find(r=>r.businessId===businessId&&r.quality==='ACCEPTED'&&r.datasetType===sheet.classification&&(stableId&&r.originalRecordIdentifier===stableId||createHash('sha256').update(JSON.stringify([r.datasetType,r.normalizedValues.date,r.normalizedValues.invoice_id,r.normalizedValues.transaction_id,r.normalizedValues.job_id,r.normalizedValues.vendor,r.normalizedValues.customer,r.normalizedValues.revenue,r.normalizedValues.net_profit,r.normalizedValues.expense,r.normalizedValues.vendor_spend,r.normalizedValues.labor_cost,r.normalizedValues.material_cost])).digest('hex')===fingerprint));if(dup){quality='POSSIBLE_DUPLICATE';duplicateOf=dup.id;duplicateCount++;}}const hasAny=Object.entries(mapped).some(([k,v])=>v!==null&&k!=='ignore');if(!hasAny){quality='INVALID';invalidCount++;}
  const row:NormalizedBusinessRecord={id:normalizedId,businessId,importId,datasetType:sheet.classification,sourceSystem,sourceProvider:sourceSystem==='Manual upload'?undefined:sourceSystem,sourceFile:input.fileName,sourceSheet:input.fileType==='xlsx'?sheet.name:undefined,sourceRow:i+2,originalRecordIdentifier:identifier||undefined,originalValues:original,normalizedValues:mapped,mappingVersion:MAPPING_VERSION,sourceComplete:input.complete,importedAt:timestamp,quality,duplicateOf};normalized.push(row);seen.push(row);
  if(quality==='INVALID')continue;const date=mapped.date;if(typeof date!=='string'||!parseDate(date)){if(amountMappings.length)warnings.push(`Row ${i+2}: dated financial analysis unavailable because a valid date is missing.`);continue;}let currency=typeof mapped.currency==='string'?mapped.currency.toUpperCase():input.currency.toUpperCase();if(!currency){warnings.push(`Row ${i+2}: currency was not provided; no financial evidence created.`);continue;}const decimals=precision[currency];if(decimals===undefined){warnings.push(`Row ${i+2}: currency ${currency} has no verified precision rule; no financial evidence created.`);continue;}for(const m of amountMappings){const field=m.targetField,raw=mapped[field];if(raw===undefined||raw===null||raw==='')continue;const minor=amountMinor(original[m.sourceColumn],decimals);if(minor===null){warnings.push(`Row ${i+2}: ${m.sourceColumn} is missing or has unsupported precision; no evidence created for ${field}.`);continue;}const metricName=metric(field,sheet.classification);if(!metricName)continue;const entityId=String(mapped.job_id||mapped.invoice_id||mapped.vendor||mapped.customer||'').trim()||undefined;const basis=input.basis?.trim()||'owner supplied; basis not specified';const sourceStableId=String(mapped.transaction_id||mapped.invoice_id||'').trim();const sourceRecordId=sourceStableId?`${sourceStableId}:${metricName}:${date}`:`${sheet.classification}:${digestRows([original,date,metricName])}`;const id=createHash('sha256').update(JSON.stringify([businessId,importId,sourceRecordId,metricName,minor,currency,date])).digest('hex');records.push({id,businessId,environment:'REAL',sourceSystem,sourceRecordId,syncId:importId,importedAt:timestamp,metric:metricName,value:minor,currency,decimals,basis,entityId,periodStart:date,periodEnd:date,complete:input.complete,verification:'OWNER_ENTERED',importId,normalizedRecordId:normalizedId,sourceFile:input.fileName,sourceSheet:input.fileType==='xlsx'?sheet.name:undefined,sourceRow:i+2,originalRecordIdentifier:identifier});}
 }
 if(duplicateCount)warnings.unshift(`${duplicateCount} row(s) share a stable record ID with an existing accepted record. These rows are excluded from financial evidence until reviewed.`);return {normalized,records,invalidCount,duplicateCount,warnings:Array.from(new Set(warnings))};
}
