import { promises as fs } from 'fs';
import path from 'path';
import { createHash, randomUUID } from 'crypto';
import { EvidenceDatabase, SourceRecord, Decision, LedgerItem, IntakeImport, NormalizedBusinessRecord, BusinessWorkspace } from './model';
import { analyze, validateRecords, measuredResult, validDate, validateOpportunityOutcome, learnOutcomes } from './engine';
const directory=path.join(process.cwd(),'.bizbetter-data');const filename=path.join(directory,'evidence-v1.json');
const globalQueue=globalThis as unknown as {evidenceQueue?:Promise<unknown>};
export const BUSINESS_ID='local-workspace';
const empty=():EvidenceDatabase=>({version:1,businessId:BUSINESS_ID,records:[],decisions:[],ledger:[],audit:[],businesses:[{id:BUSINESS_ID,name:'My Business',createdAt:new Date().toISOString()}],imports:[],normalizedRecords:[]});
export async function readDatabase():Promise<EvidenceDatabase>{
 try{const db=JSON.parse(await fs.readFile(filename,'utf8')) as EvidenceDatabase;if(db.version!==1||db.businessId!==BUSINESS_ID)throw new Error('Unsupported evidence database.');db.businesses??=[{id:BUSINESS_ID,name:'My Business',createdAt:new Date().toISOString()}];db.imports??=[];db.normalizedRecords??=[];for(const id of Array.from(new Set(db.records.map(r=>r.businessId))))validateRecords(db.records.filter(r=>r.businessId===id),id);let previous='';for(const a of db.audit){const {hash,...event}=a;if(event.previousHash!==previous||createHash('sha256').update(JSON.stringify(event)).digest('hex')!==hash)throw new Error('Audit chain is invalid.');previous=hash;}return db;}
 catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return empty();throw e;}
}
async function mutate<T>(action:string,operation:(db:EvidenceDatabase)=>T):Promise<T>{
 const next=(globalQueue.evidenceQueue||Promise.resolve()).catch(()=>{}).then(async()=>{const db=await readDatabase(),result=operation(db),event={id:randomUUID(),at:new Date().toISOString(),action,objectId:typeof result==='object'&&result&&'id' in result?String(result.id):'workspace',previousHash:db.audit.at(-1)?.hash||''};db.audit.push({...event,hash:createHash('sha256').update(JSON.stringify(event)).digest('hex')});await fs.mkdir(directory,{recursive:true});const temporary=filename+'.tmp';await fs.writeFile(temporary,JSON.stringify(db),{mode:0o600});await fs.rename(temporary,filename);return result;});globalQueue.evidenceQueue=next;return next;
}
export function activeRecords(records:SourceRecord[]){const superseded=new Set(records.map(r=>r.supersedesId).filter(Boolean));return records.filter(r=>!superseded.has(r.id));}
export async function appendRecords(records:SourceRecord[]){for(const id of Array.from(new Set(records.map(r=>r.businessId))))validateRecords(records.filter(r=>r.businessId===id),id);return mutate('SOURCE_IMPORT',db=>{const ids=new Set(db.records.map(r=>r.id));let added=0;for(const r of records)if(!ids.has(r.id)){if(r.verification==='PROVIDER'){const previous=activeRecords(db.records).find(p=>p.businessId===r.businessId&&p.sourceSystem===r.sourceSystem&&p.sourceRecordId===r.sourceRecordId&&p.metric===r.metric&&p.periodStart===r.periodStart&&p.periodEnd===r.periodEnd);if(previous)r.supersedesId=previous.id;}db.records.push(r);ids.add(r.id);added++;}return {recordsAdded:added,totalRecords:db.records.length};});}
export async function createBusiness(name:string,industry?:string):Promise<BusinessWorkspace>{if(!name.trim()||name.trim().length>120)throw new Error('Business name must be 1–120 characters.');return mutate('BUSINESS_CREATE',db=>{const business={id:randomUUID(),name:name.trim(),industry:industry?.trim().slice(0,100)||undefined,createdAt:new Date().toISOString()};db.businesses!.push(business);return business;});}
export async function listBusinesses(){const db=await readDatabase();return db.businesses||[];}
export async function commitIntake(input:{batch:IntakeImport;normalized:NormalizedBusinessRecord[];records:SourceRecord[]}){for(const id of Array.from(new Set(input.records.map(r=>r.businessId))))validateRecords(input.records.filter(r=>r.businessId===id),id);return mutate('DATA_INTAKE_COMMIT',db=>{if(!db.businesses!.some(b=>b.id===input.batch.businessId))throw new Error('Unknown business workspace.');if(db.imports!.some(i=>i.id===input.batch.id))throw new Error('This upload was already committed.');const ids=new Set(db.records.map(r=>r.id));for(const r of input.records){if(ids.has(r.id))throw new Error('An identical normalized evidence record is already stored. Review the duplicate report before importing.');db.records.push(r);ids.add(r.id);}db.imports!.push(input.batch);db.normalizedRecords!.push(...input.normalized);return {importId:input.batch.id,records:input.records.length,normalized:input.normalized.length};});}
export async function rejectImport(importId:string,businessId:string){return mutate('DATA_INTAKE_REJECT',db=>{const item=db.imports!.find(i=>i.id===importId&&i.businessId===businessId);if(!item||item.status!=='COMMITTED')throw new Error('Committed import not found for this business.');item.status='REJECTED';for(const r of db.normalizedRecords!)if(r.importId===importId)r.quality='INVALID';return {importId,status:item.status};});}
export async function resolveDuplicate(id:string,businessId:string,decision:'distinct'|'duplicate'){return mutate('DATA_DUPLICATE_REVIEW',db=>{const row=db.normalizedRecords!.find(r=>r.id===id&&r.businessId===businessId&&r.quality==='POSSIBLE_DUPLICATE');if(!row)throw new Error('Possible duplicate not found in this business.');row.quality=decision==='distinct'?'ACCEPTED':'INVALID';return {recordId:id,decision,quality:row.quality,sourceRecordCount:db.records.filter(r=>r.normalizedRecordId===id).length};});}
function businessRecords(db:EvidenceDatabase,businessId:string){if(!db.businesses!.some(b=>b.id===businessId))throw new Error('Unknown business workspace.');const imports=db.imports!.filter(i=>i.businessId===businessId);const committed=new Set(imports.filter(i=>i.status==='COMMITTED').map(i=>i.id));const normalized=db.normalizedRecords!.filter(r=>r.businessId===businessId&&committed.has(r.importId));const unresolved=new Set(normalized.filter(r=>r.quality!=='ACCEPTED').map(r=>r.id));const records=activeRecords(db.records.filter(r=>r.businessId===businessId&&(!r.importId||committed.has(r.importId))&&(!r.normalizedRecordId||!unresolved.has(r.normalizedRecordId))));return records;}
export async function intakeWorkspace(businessId=BUSINESS_ID){const db=await readDatabase(),business=db.businesses!.find(b=>b.id===businessId);if(!business)throw new Error('Unknown business workspace.');const imports=db.imports!.filter(i=>i.businessId===businessId);const committed=new Set(imports.filter(i=>i.status==='COMMITTED').map(i=>i.id));const normalized=db.normalizedRecords!.filter(r=>r.businessId===businessId&&committed.has(r.importId));const records=businessRecords(db,businessId);return {business,imports,normalized,analysis:analyze(records,businessId),sourceRecords:records,decisions:db.decisions.filter(d=>d.businessId===businessId),ledger:db.ledger.filter(i=>i.businessId===businessId)};}
export async function workspace(businessId=BUSINESS_ID){const result=await intakeWorkspace(businessId);const db=await readDatabase();return {...result.analysis,records:result.sourceRecords,decisions:result.decisions,ledger:result.ledger,audit:db.audit,businessId,learnings:learnOutcomes(result.sourceRecords,result.decisions,result.ledger)};}
export async function recordDecision(input:Partial<Decision>){const businessId=input.businessId||BUSINESS_ID;return mutate('OWNER_DECISION',db=>{
 const finding=analyze(businessRecords(db,businessId),businessId).findings.find(f=>f.id===input.findingId);if(!finding)throw new Error('A current evidence-backed finding is required.');
 if(!['ACCEPTED','MODIFIED','REJECTED'].includes(input.decision||'')||!input.owner?.trim()||!input.notes?.trim())throw new Error('Decision, owner and notes are required.');
 const record:Decision={id:randomUUID(),businessId,findingId:finding.id,decision:input.decision!,owner:input.owner,notes:input.notes,createdAt:new Date().toISOString(),evidenceSnapshot:finding,baselineIds:[],afterIds:[]};db.decisions.push(record);return record;});}
export async function changeStage(input:{businessId?:string;findingId:string;state:LedgerItem['state'];validatedBy?:string;validationNotes?:string;decisionId?:string;implementationDate?:string;baselineIds?:string[];afterIds?:string[];confounderReview?:Record<string,string>}){const businessId=input.businessId||BUSINESS_ID;return mutate('OPPORTUNITY_STAGE',db=>{
 const f=analyze(businessRecords(db,businessId),businessId).findings.find(f=>f.id===input.findingId);if(!f?.opportunity)throw new Error('This observation is not a quantified savings opportunity.');
 const states=['POTENTIAL','VALIDATED','IMPLEMENTED','REALIZED'];if(!states.includes(input.state))throw new Error('Invalid opportunity stage.');
 let item=db.ledger.find(i=>i.businessId===businessId&&i.findingId===f.id);if(!item){if(input.state!=='POTENTIAL')throw new Error('Start at identified potential.');item={id:randomUUID(),businessId,findingId:f.id,findingSnapshot:f,state:'POTENTIAL'};db.ledger.push(item);return item;}
 if(states.indexOf(input.state)!==states.indexOf(item.state)+1)throw new Error('Stages must advance sequentially with evidence.');
 if(input.state==='VALIDATED'){if(!input.validatedBy?.trim()||!input.validationNotes?.trim())throw new Error('A named validator and reconciliation notes are required.');item.validationNotes=input.validationNotes;item.validatedBy=input.validatedBy;item.validatedAt=new Date().toISOString();}
 if(input.state==='IMPLEMENTED'){const d=db.decisions.find(d=>d.businessId===businessId&&d.id===input.decisionId&&d.findingId===f.id&&d.decision!=='REJECTED');if(!d||!input.implementationDate||!validDate(input.implementationDate)||input.implementationDate>new Date().toISOString().slice(0,10))throw new Error('Recorded owner decision and valid implementation date required.');d.implementationDate=input.implementationDate;item.decisionId=d.id;}
 if(input.state==='REALIZED'){const d=db.decisions.find(d=>d.businessId===businessId&&d.id===item!.decisionId);if(!d)throw new Error('Implementation decision is missing.');const candidate={...d,baselineIds:input.baselineIds||[],afterIds:input.afterIds||[],confounderReview:input.confounderReview};const result=validateOpportunityOutcome(f,candidate,businessRecords(db,businessId));Object.assign(d,candidate);item.result=result;}
 item.state=input.state;return item;});}
